---
abstract: "Extract text from Word files\r"
author:
  - 'Stuart Watt <stuart@morungos.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120630'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Extract-Word
requires:
  Encode: 0
  IO::File: 0
  OLE::Storage_Lite: 0
  POSIX: 0
  perl: 5.008000
version: 0.04
